### ISSUE TITLE
Add Padding

### ISSUE THREAD

**Issue by shahdivyank** [UCR-Solar-Car/solarcar-website#130]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/36285610/212544770-4bb4b12c-6e0c-4ef9-9a2a-6f69e5605f44.png">

**Comment by mgolwalla** [comment]
did you pull? this is what i have 
![image](https://user-images.githubusercontent.com/56405905/213845253-5349cba5-343f-4601-aa04-53ccfad621be.png)

i think it looks good ?

**Comment by shahdivyank** [comment]
> did you pull? this is what i have ![image](https://user-images.githubusercontent.com/56405905/213845253-5349cba5-343f-4601-aa04-53ccfad621be.png)
> 
> i think it looks good ?

L O L, this is funny content fr, yea looks like we chillin then
