### ISSUE TITLE
Rearrange Teams

### ISSUE THREAD

**Issue by shahdivyank** [UCR-Solar-Car/solarcar-website#86]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/36285610/209542630-21321ee9-d71e-472c-8be9-d29a2e451963.png">

- Add Justin Yee to Driver Interface

- The order is very linear, need to mix it up more
- Use the following order: 
- Electrical, Telemetry, Mechanical, Software, Business

**Comment by Jyro88** [comment]
I'm the only one missing? Feels kinda targeted tbh smh

**Comment by shahdivyank** [comment]
> I'm the only one missing? Feels kinda targeted tbh smh

There was a thread for this open in Driver Interface, this one on you sir 😐
